Transform: AWS::Serverless-2016-10-31

Resources:
# ============== Non AppSync resources ==============
  NotesTable:
    Type: "AWS::Serverless::SimpleTable"

  AllMyNotes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/all_my_notes/
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          API_KEY: !GetAtt SamGraphQl.OneKeyToRuleThemAll.ApiKey
          GRAPHQL_URL: !GetAtt SamGraphQl.GraphQLUrl
      Connectors:
        ReadNotes:
          Properties:
            Destination:
              Id: NotesTable
            Permissions:
              - Read

# ================== Graph QL resources ============================
  SamGraphQl:
    Type: "AWS::Serverless::GraphQLApi"
    Properties:
      Name: MyNotes
      SchemaUri: "schema-v1.graphql"
      MappingConfig:
        PathToCode: "s3://graph-ql-demo/"
        Runtime:
          Name: APPSYNC_JS
          RuntimeVersion: "1.0.0"
      AuthenticationType: API_KEY
      ApiKeys:
        OneKeyToRuleThemAll:
          ExpiresOn: 2023-10-17
        OnlyToRead: {}
      DynamoDbDataSources:
        NotesReadWriteDataSource:
          TableName: !Ref NotesTable
        NotesReadDataSource:
          TableName: !Ref NotesTable
          Permissions:
            - Read
      LambdaResolvers:
        Query:
          AllMyNotes: 
            LambdaArn: !GetAtt AllMyNotes.Arn
          SayHello:
            LambdaArn: !GetAtt HelloLambda.Arn
            CodeUri: s3://my-library/utilitites/sayHello.js
        Mutation:
          ChangeName:
            LambdaArn: !GetAtt ChangeNameLambda.Arn
            ServiceRoleArn: !GetAtt AppSyncChangeNameLambdaInvocationRole.Arn
      AppSyncResolvers:
        # Type: Note.NoteId
        Mutation:
          SaveNote:
            DataSourceName: NotesReadWriteDataSource
            GenerateCode: True
            Functions: # PipelineFunction
              - SaveNote: {}
              - Notify-version11111
              - MakeMeCoffee
              - PlayMusic:
                  Id: !GetAtt AppSyncPlayMusicFunction.FunctionId
        # TODO: add when AppSync supports JS for unit resolvers in CFN
        # Query: # Query is obviously enable 
        #   GetNote:
        #     DataSourceName: TableReadOnlyDataSource
      Functions: # PipelineFunction - change?
        Notify-version11111:
          Name: Notify
          DataSourceName: NONE
        MakeMeCoffee:
          CodeUri: "s3://my-library/utilitites/makeCoffee.js"
          DataSourceName: !GetAtt HttpApiDataSource.Name

  HttpApiDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt SamGraphQl.ApiId
      Name: CoffeeMaker
      Type: HTTP
      HttpConfig:
        Endpoint: "https://remote-coffee.machine/"

  AppSyncDeleteNoteResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt SamGraphQl.ApiId
      DataSourceName: !GetAtt SamGraphQl.DataSource.TableReadWriteDataSource.Name
      TypeName: Mutation
      FieldName: deleteNote
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "DeleteItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($context.args.id)
          }
        }
      ResponseMappingTemplate: "$util.toJson($context.result)"

  AppSyncPlayMusicFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties: 
      ApiId: !GetAtt SamGraphQl.ApiId
      CodeS3Location: "s3://my-library/utilitites/makeCoffee.js"
      DataSourceName: NONE
      Name: PlayMusic
      Runtime: 
        Name: APPSYNC_JS
        RuntimeVersion: "1.0.0"
