version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "GraphQLDemo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u0axphxnebcb"
s3_prefix = "GraphQLDemo"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "APIName=\"MyNotes\""
image_repositories = []
