Transform: AWS::Serverless-2016-10-31

Resources:
  DynamoDBPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: posts-table
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SuperCoolAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      SchemaInline: |
        schema {
            query: Query
            mutation: Mutation
        }

        type Query {
            getPost(id: String!): Post
        }

        type Mutation {
            addPost(
            author: String!,
            title: String!,
            content: String!,
            ): Post!
        }

        type Post {
            id: String!
            author: String
            title: String
            content: String
            ups: Int!
            downs: Int!
            version: Int!
        }
      Defaults:
        ResolversAndPipelineFunctions: 
          Runtime:
            Name: APPSYNC_JS
            RuntimeVersion: "1.0.0"
        PipelineFunctions:
          DataSource: PostsDataSource
      Auth:
        Type: API_KEY
      ApiKeys:
      - MyApiKey: {}
      DataSources:
        DynamoDb:
          PostsDataSource:
            TableName: !Ref DynamoDBPostsTable
      PipelineFunctions:
        formatPostItem:
          DataSource: NONE
          InlineCode: |
            import { util } from '@aws-appsync/utils';

            export function request(ctx) {
              const id = util.autoId();
              const { ...values } = ctx.args;
              values.ups = 1;
              values.downs = 0;
              values.version = 1;
              return { 
                payload: { 
                  key: {id},
                  values: values 
                }
              }
            }

            export function response(ctx) {
              return ctx.result;
            }
        createPostItem:
          InlineCode: |
            import { util } from '@aws-appsync/utils';

            export function request(ctx) {
              return dynamoDBGetItemRequest({ id: ctx.args.id });
            }

            export function response(ctx) {
              return ctx.result;
            }

            /**
            * A helper function to get a DynamoDB item
            */
            function dynamoDBGetItemRequest(key) {
              return {
                operation: 'GetItem',
                key: util.dynamodb.toMapValues(key),
              };
            }
        getPostFromTable:
          InlineCode: |
            import { util } from '@aws-appsync/utils';

            export function request(ctx) {
              return dynamoDBGetItemRequest({ id: ctx.args.id });
            }

            export function response(ctx) {
              return ctx.result;
            }

            /**
            * A helper function to get a DynamoDB item
            */
            function dynamoDBGetItemRequest(key) {
              return {
                operation: 'GetItem',
                key: util.dynamodb.toMapValues(key),
              };
            }
      Resolvers:
        Mutation:
          addPost:
            Pipeline:
            - formatPostItem
            - createPostItem
        Query:
          getPost:
            Pipeline:
            - getPostFromTable

Outputs:
  SuperCoolAPI:
    Description: AppSync API
    Value: !GetAtt SuperCoolAPI.GraphQLUrl
  MyApiKey:
    Description: API Key for authentication
    Value: !GetAtt MyApiKey.ApiKey
Metadata:
  SamTransformTest: true
