Transform: AWS::Serverless-2016-10-31

Resources:
  NotesTable:
    Type: "AWS::Serverless::SimpleTable"
  ObservationsTable:
    Type: "AWS::Serverless::SimpleTable"

  SamGraphQl:
    Type: "AWS::Serverless::GraphQLApi"
    Properties:
      Name: MyNotes
      SchemaUri: "schema.graphql"
      Defaults:
        Runtime:
          Name: APPSYNC_JS
          RuntimeVersion: "1.0.0"
      Auth:
        Type: API_KEY
      ApiKeys:
        OneKeyToRuleThemAll:
          ExpiresOn: 2023-10-17
      DynamoDbDataSources:
        NotesTableDataSource:
          TableName: !Ref NotesTable
        ObservationsTableDataSource:
          TableName: !Ref ObservationsTable
      AppSyncResolvers:
        Mutation:
          createNote:
            Pipeline:
              - readObservataions
              - transformObservations
              - createNote
              - notify
          getNote:
            Caching:
              Ttl: 3600
            DataSource: NotesTableDataSource
            Pipeline:
            - getNote:
                CodeUri: "functions/getNote.js"
          deleteNote:
            Pipeline:
            - deleteNote:
                CodeUri: "functions/deleteNote.js"
                DataSource: NotesTableDataSource
            - notify
      Functions:
        readObservataions: 
          CodeUri: "functions/readObservataions.js"
          DataSource: ObservationsTableDataSource
        transformObservations: 
          CodeUri: "functions/transformObservations.js"
          DataSource: ObservationsTableDataSource
        createNote:
          CodeUri: "functions/createNote.js"
          DataSource: NotesTableDataSource
        notify:
          CodeUri: "functions/notify.js"
          DataSource: NONE # this None is case insensitive
