Transform: AWS::Serverless-2016-10-31

Resources:
  NotesTable:
    Type: "AWS::Serverless::SimpleTable"

  SamCliGraphQlTest:
    Type: "AWS::Serverless::GraphQLApi"
    Properties:
      Name: MyNotes
      SchemaUri: "schema.graphql"
      Defaults:
        Runtime:
          Name: APPSYNC_JS
          Version: "1.0.0"
        Functions:
          DataSourceName: NotesTableDataSource
      Auth:
        Type: AWS_IAM
      DynamoDBDataSources:
        NotesTableDataSource:
          TableName: NotesTable
      Resolvers:
        Query:
          getNote:
            CodeUri: "./resolvers/getNote.js"
            Pipeline:
            - getNote
          saveNote:
            Pipeline:
            - saveNote
      Functions:
        saveNote:
          CodeUri: "./functions/saveNote.js"
        deleteNote:
          CodeUri: "./functions/deleteNote.js"
        getNote:
          InlineCode: |
            import { util } from '@aws-appsync/utils';

            export function request(ctx) {
              return dynamoDBGetItemRequest({ id: ctx.args.id });
            }

            export function response(ctx) {
              return ctx.result;
            }

            /**
            * A helper function to get a DynamoDB item
            */
            function dynamoDBGetItemRequest(key) {
              return {
                operation: 'GetItem',
                key: util.dynamodb.toMapValues(key),
              };
            }
